const dateLabels = [
  'Apr 01', 'Apr 04', 'Apr 08', 'Apr 12', 'Apr 16', 'Apr 20',
  'Apr 24', 'Apr 28', 'May 02', 'May 06', 'May 10', 'May 14'
];

const buildSeries = ({ base, drift, volatility, decimals = 2, isVolume = false }) => {
  let current = base;
  return dateLabels.map((date, index) => {
    const seasonal = Math.sin(index / 2.4 + drift) * volatility;
    const trendBias = drift * (index / dateLabels.length);
    const adjustment = (seasonal + trendBias) / 100;
    current *= 1 + adjustment;

    const value = isVolume ? Math.round(current / 1000) * 1000 : Number(current.toFixed(decimals));
    return { date, value };
  });
};

function createAgent(id, name, signal, confidence, factors, explanation) {
  return {
    id,
    name,
    signal,
    confidence,
    factors,
    explanation,
  };
}

function buildProfile(config) {
  const priceHistory = buildSeries({
    base: config.price,
    drift: config.priceDrift,
    volatility: config.priceVolatility,
    decimals: 2,
  });

  const volumeHistory = buildSeries({
    base: config.volume,
    drift: config.volumeDrift,
    volatility: config.volumeVolatility,
    decimals: 0,
    isVolume: true,
  });

  const rsiHistory = buildSeries({
    base: config.rsi,
    drift: config.rsiDrift,
    volatility: config.rsiVolatility,
    decimals: 1,
  });

  const portfolioHistory = buildSeries({
    base: config.portfolioValue,
    drift: config.portfolioDrift,
    volatility: config.portfolioVolatility * 0.8,
    decimals: 0,
  });

  const fundamentalSignal = config.revenueGrowth > 9 ? 'Bullish' : config.revenueGrowth > 5 ? 'Neutral' : 'Bearish';
  const technicalSignal = config.rsi > 58 ? 'Bullish' : config.rsi < 42 ? 'Bearish' : 'Neutral';
  const sentimentSignal = config.sentimentScore > 0.55 ? 'Positive' : config.sentimentScore < 0.45 ? 'Negative' : 'Neutral';
  const valuationSignal = config.intrinsicValue > config.price * 1.04 ? 'Undervalued' : config.intrinsicValue < config.price * 0.96 ? 'Overvalued' : 'Fairly Valued';
  const riskSignal = config.riskScore < 35 ? 'Low' : config.riskScore < 60 ? 'Medium' : 'High';

  const agents = [
    createAgent(
      'fundamental',
      'Fundamental Analyst',
      fundamentalSignal,
      config.fundamentalConfidence,
      [
        `Revenue growth ${config.revenueGrowth}%`,
        `EPS ${config.eps}`,
        `P/E ${config.peRatio} against sector benchmark`,
      ],
      `${config.company} is showing durable earnings expansion, which supports a structured long-term bullish view in this simulated analysis.`
    ),
    createAgent(
      'technical',
      'Technical Analyst',
      technicalSignal,
      config.technicalConfidence,
      [
        `50-day average above 200-day trend`,
        `RSI near ${config.rsi}`,
        `Momentum score ${config.momentum}`,
      ],
      `Trend strength and momentum remain constructive, while the technical setup indicates sustained participation without overstretched conditions.`
    ),
    createAgent(
      'sentiment',
      'Sentiment Analyst',
      sentimentSignal,
      config.sentimentConfidence,
      [
        `News sentiment ${config.sentimentScore.toFixed(2)}`,
        `Analyst chatter ${config.analystChatter}`,
        `Social tone ${config.socialTone}`,
      ],
      `Market narratives are balanced but generally constructive, with positive earnings commentary offset by occasional macro caution.`
    ),
    createAgent(
      'valuation',
      'Valuation Analyst',
      valuationSignal,
      config.valuationConfidence,
      [
        `Intrinsic value $${config.intrinsicValue.toFixed(2)}`,
        `Current price $${config.price.toFixed(2)}`,
        `Margin of safety ${config.marginOfSafety}%`,
      ],
      `The model indicates that current pricing reflects a reasonable premium relative to estimated fair value, leaving limited upside if sentiment fades.`
    ),
    createAgent(
      'risk',
      'Risk Analyst',
      riskSignal,
      config.riskConfidence,
      [
        `Volatility ${config.volatility}%`,
        `Max drawdown ${config.maxDrawdown}%`,
        `VaR ${config.var}%`,
      ],
      `Risk remains manageable, though macro sensitivity and concentrated positioning could amplify downside during broad-market pullbacks.`
    ),
    createAgent(
      'strategy',
      'Investor Strategy Agent',
      config.strategySignal,
      config.strategyConfidence,
      [
        `Value bias ${config.valueBias}`,
        `Positioning ${config.positioning}`,
        `Portfolio fit ${config.portfolioFit}`,
      ],
      `A disciplined value-investing lens favors selective accumulation when quality metrics remain intact and downside risk is contained.`
    ),
  ];

  return {
    ...config,
    priceHistory,
    volumeHistory,
    rsiHistory,
    portfolioHistory,
    agents,
    riskMetrics: {
      volatility: config.volatility,
      maxDrawdown: config.maxDrawdown,
      var: config.var,
      beta: config.beta,
    },
  };
}

export const stockProfiles = {
  AAPL: buildProfile({
    ticker: 'AAPL',
    company: 'Apple Inc.',
    price: 214.82,
    priceDrift: 1.4,
    priceVolatility: 1.8,
    changePct: 1.48,
    volume: 61520000,
    volumeDrift: 1.2,
    volumeVolatility: 2.3,
    marketTrend: 'Bullish',
    volatilityLevel: 'Moderate',
    revenueGrowth: 12.8,
    eps: 6.84,
    peRatio: 31.4,
    intrinsicValue: 221.12,
    marginOfSafety: 4.8,
    rsi: 61.8,
    rsiDrift: 1.1,
    rsiVolatility: 5.4,
    momentum: 62,
    sentimentScore: 0.71,
    analystChatter: 'Positive',
    socialTone: 'Constructive',
    fundamentalConfidence: 84,
    technicalConfidence: 81,
    sentimentConfidence: 77,
    valuationConfidence: 73,
    riskConfidence: 68,
    riskScore: 42,
    maxDrawdown: 18.3,
    var: 9.2,
    volatility: 22.4,
    beta: 1.12,
    strategySignal: 'Bullish',
    strategyConfidence: 80,
    valueBias: 'Quality growth',
    positioning: 'Selective',
    portfolioFit: 'Strong',
    portfolioValue: 100000,
    portfolioDrift: 1.6,
    portfolioVolatility: 5.4,
  }),
  MSFT: buildProfile({
    ticker: 'MSFT',
    company: 'Microsoft Corp.',
    price: 446.91,
    priceDrift: 1.9,
    priceVolatility: 2.0,
    changePct: 1.94,
    volume: 28700000,
    volumeDrift: 1.0,
    volumeVolatility: 2.1,
    marketTrend: 'Bullish',
    volatilityLevel: 'Moderate',
    revenueGrowth: 15.2,
    eps: 13.08,
    peRatio: 34.2,
    intrinsicValue: 467.6,
    marginOfSafety: 4.3,
    rsi: 64.1,
    rsiDrift: 1.2,
    rsiVolatility: 4.8,
    momentum: 68,
    sentimentScore: 0.74,
    analystChatter: 'Strong positive',
    socialTone: 'Optimistic',
    fundamentalConfidence: 87,
    technicalConfidence: 83,
    sentimentConfidence: 82,
    valuationConfidence: 76,
    riskConfidence: 72,
    riskScore: 38,
    maxDrawdown: 16.1,
    var: 8.8,
    volatility: 19.7,
    beta: 0.97,
    strategySignal: 'Bullish',
    strategyConfidence: 83,
    valueBias: 'Durable cash flow',
    positioning: 'Conviction',
    portfolioFit: 'Excellent',
    portfolioValue: 100000,
    portfolioDrift: 1.7,
    portfolioVolatility: 5.1,
  }),
  GOOGL: buildProfile({
    ticker: 'GOOGL',
    company: 'Alphabet Inc.',
    price: 180.42,
    priceDrift: 1.2,
    priceVolatility: 1.9,
    changePct: 0.94,
    volume: 32150000,
    volumeDrift: 1.1,
    volumeVolatility: 2.2,
    marketTrend: 'Neutral',
    volatilityLevel: 'Moderate',
    revenueGrowth: 10.6,
    eps: 7.01,
    peRatio: 25.7,
    intrinsicValue: 181.6,
    marginOfSafety: 0.7,
    rsi: 55.2,
    rsiDrift: 0.8,
    rsiVolatility: 4.6,
    momentum: 54,
    sentimentScore: 0.58,
    analystChatter: 'Positive',
    socialTone: 'Balanced',
    fundamentalConfidence: 79,
    technicalConfidence: 69,
    sentimentConfidence: 72,
    valuationConfidence: 66,
    riskConfidence: 64,
    riskScore: 46,
    maxDrawdown: 20.4,
    var: 10.1,
    volatility: 23.8,
    beta: 1.08,
    strategySignal: 'Neutral',
    strategyConfidence: 67,
    valueBias: 'Quality compounder',
    positioning: 'Measured',
    portfolioFit: 'Good',
    portfolioValue: 100000,
    portfolioDrift: 1.4,
    portfolioVolatility: 5.7,
  }),
  AMZN: buildProfile({
    ticker: 'AMZN',
    company: 'Amazon.com Inc.',
    price: 190.68,
    priceDrift: 1.7,
    priceVolatility: 2.4,
    changePct: 1.82,
    volume: 45400000,
    volumeDrift: 1.5,
    volumeVolatility: 2.8,
    marketTrend: 'Bullish',
    volatilityLevel: 'High',
    revenueGrowth: 11.6,
    eps: 5.91,
    peRatio: 32.3,
    intrinsicValue: 198.4,
    marginOfSafety: 4.0,
    rsi: 59.5,
    rsiDrift: 1.0,
    rsiVolatility: 6.1,
    momentum: 60,
    sentimentScore: 0.69,
    analystChatter: 'Positive',
    socialTone: 'Constructive',
    fundamentalConfidence: 82,
    technicalConfidence: 79,
    sentimentConfidence: 76,
    valuationConfidence: 71,
    riskConfidence: 66,
    riskScore: 52,
    maxDrawdown: 23.2,
    var: 11.4,
    volatility: 26.8,
    beta: 1.19,
    strategySignal: 'Bullish',
    strategyConfidence: 78,
    valueBias: 'Scale efficiency',
    positioning: 'Growth tilt',
    portfolioFit: 'Strong',
    portfolioValue: 100000,
    portfolioDrift: 1.8,
    portfolioVolatility: 6.2,
  }),
  TSLA: buildProfile({
    ticker: 'TSLA',
    company: 'Tesla Inc.',
    price: 248.71,
    priceDrift: 0.8,
    priceVolatility: 4.1,
    changePct: -0.72,
    volume: 72140000,
    volumeDrift: 1.7,
    volumeVolatility: 3.1,
    marketTrend: 'Neutral',
    volatilityLevel: 'High',
    revenueGrowth: 8.4,
    eps: 4.62,
    peRatio: 53.8,
    intrinsicValue: 233.9,
    marginOfSafety: -6.0,
    rsi: 48.5,
    rsiDrift: -0.5,
    rsiVolatility: 8.2,
    momentum: 46,
    sentimentScore: 0.49,
    analystChatter: 'Mixed',
    socialTone: 'Cautious',
    fundamentalConfidence: 62,
    technicalConfidence: 58,
    sentimentConfidence: 55,
    valuationConfidence: 48,
    riskConfidence: 74,
    riskScore: 71,
    maxDrawdown: 31.8,
    var: 14.6,
    volatility: 35.1,
    beta: 1.64,
    strategySignal: 'Neutral',
    strategyConfidence: 59,
    valueBias: 'Speculative growth',
    positioning: 'Selective',
    portfolioFit: 'Risky',
    portfolioValue: 100000,
    portfolioDrift: 0.9,
    portfolioVolatility: 8.5,
  }),
  NVDA: buildProfile({
    ticker: 'NVDA',
    company: 'NVIDIA Corp.',
    price: 126.28,
    priceDrift: 2.8,
    priceVolatility: 3.3,
    changePct: 2.35,
    volume: 51230000,
    volumeDrift: 2.1,
    volumeVolatility: 2.9,
    marketTrend: 'Bullish',
    volatilityLevel: 'High',
    revenueGrowth: 18.5,
    eps: 4.84,
    peRatio: 26.1,
    intrinsicValue: 138.2,
    marginOfSafety: 9.4,
    rsi: 66.9,
    rsiDrift: 1.8,
    rsiVolatility: 7.5,
    momentum: 72,
    sentimentScore: 0.78,
    analystChatter: 'Very positive',
    socialTone: 'Bullish',
    fundamentalConfidence: 88,
    technicalConfidence: 86,
    sentimentConfidence: 81,
    valuationConfidence: 78,
    riskConfidence: 70,
    riskScore: 54,
    maxDrawdown: 27.6,
    var: 12.9,
    volatility: 29.4,
    beta: 1.43,
    strategySignal: 'Bullish',
    strategyConfidence: 84,
    valueBias: 'AI leadership',
    positioning: 'Strong momentum',
    portfolioFit: 'Excellent',
    portfolioValue: 100000,
    portfolioDrift: 2.4,
    portfolioVolatility: 7.4,
  }),
};

export const stockList = Object.keys(stockProfiles).map((ticker) => ({
  ticker,
  company: stockProfiles[ticker].company,
  price: stockProfiles[ticker].price,
}));

export const dashboardSections = [
  'Dashboard',
  'Agent Analysis',
  'Consensus',
  'Backtesting',
  'Risk Analysis',
  'About Research',
];
